<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_fullname</name>
   <tag></tag>
   <elementGuidId>27b3e768-375d-4bd6-8d46-28c9e94bf322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>720756fb-08ee-455a-a67a-0094a9f2b1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_name</value>
      <webElementGuid>bfd29b00-5b15-48df-9f7b-47ae56729010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1lq7emp</value>
      <webElementGuid>95833625-cdf8-45ec-b983-606cefaeb91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f717102c-1190-44c6-9b15-cc13a7030fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_name&quot;)</value>
      <webElementGuid>c89ff261-0eac-4254-8fe1-97eab3fb5d1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_name']</value>
      <webElementGuid>db2a57bd-f111-46dd-91b5-998e598da24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[2]/div/div/input</value>
      <webElementGuid>3b3a3dab-aa39-4453-88ba-137eb0a4b1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3d59cef3-32fe-46ee-bade-585687ccb001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_name' and @type = 'text']</value>
      <webElementGuid>c257cfa3-27cd-440c-aee8-404187384aa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
