<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone_number</name>
   <tag></tag>
   <elementGuidId>bbca403f-ffb7-4d10-a68b-6059febea916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a4a7ec7-4f47-46ed-88d3-1f7be2ff91c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_phone</value>
      <webElementGuid>29c8fd93-7f76-42e1-aff3-4dffd78d9895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1lq7emp</value>
      <webElementGuid>2fcfae2e-dfc9-46ab-9dec-87dad46ca69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7e18da3-c987-406b-9025-2a6de1dd8d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_phone&quot;)</value>
      <webElementGuid>2e540d66-de36-482c-891e-6a702e19b9a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_phone']</value>
      <webElementGuid>dbc4f643-e41e-4d06-9dd9-539fc6bc0396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[3]/div/div[2]/div/div/span/input</value>
      <webElementGuid>41fe4235-0955-4952-9b9b-34ec9c5de3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/span/input</value>
      <webElementGuid>f9bf6685-7796-42e6-9090-6b5cd211eae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_phone' and @type = 'text']</value>
      <webElementGuid>8ab0d1b3-2d96-433b-8225-ba500215912a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
