<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_testingqa</name>
   <tag></tag>
   <elementGuidId>877c8d4a-9641-4e7f-8687-28748029fc24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='basic_message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>97a5ede4-aecc-4e30-8b16-18a4ff33366b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_message</value>
      <webElementGuid>e80ac793-089b-46b8-a88d-cb75f99f1de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success css-1lq7emp</value>
      <webElementGuid>bac942c6-cb6d-4d85-af59-0f20bb2e6f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testingqa</value>
      <webElementGuid>b2b121fc-85b1-40f3-a46e-6027f3c19632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_message&quot;)</value>
      <webElementGuid>ab3cbf05-dfd3-4557-bd9c-e0dcb0c7dbcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='basic_message']</value>
      <webElementGuid>544fcf40-affa-4f8c-bda8-0b01097e0a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>22a8591e-3e14-46df-b3a1-68a534ff30b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[1]/following::textarea[1]</value>
      <webElementGuid>f8815a37-86b0-4bca-a75a-276e20ab2934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='walk in'])[1]/following::textarea[1]</value>
      <webElementGuid>50342ad3-f393-4d9a-b0ac-f2eb3ff58830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Attachment'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4957a0e1-dbd4-45b1-be5d-5ad976f76ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Attachment'])[2]/preceding::textarea[1]</value>
      <webElementGuid>9cbdf882-cae5-4d01-9e33-c5810319882b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='testingqa']/parent::*</value>
      <webElementGuid>be24f6a1-4971-4924-9c25-475db35208df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9992fdab-59de-40f5-b829-ad80cb0198a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'basic_message' and (text() = 'testingqa' or . = 'testingqa')]</value>
      <webElementGuid>70533c44-a72f-442b-aba3-688fdfc4633c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
