<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subject_basic_subject</name>
   <tag></tag>
   <elementGuidId>4d952a3a-eb11-4e8e-bea3-0025cd908b2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_subject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_subject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cdc09d8-064c-4efa-bbf5-b11920dff0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_subject</value>
      <webElementGuid>c65a3137-8563-475b-a992-ba52769a33a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6526c4ae-b303-4cb2-91de-e420b178ac13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1lq7emp</value>
      <webElementGuid>26b2373b-f246-485d-a996-e78edec9d4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>345b86b5-5650-4e31-b9ac-00e13288788c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_subject&quot;)</value>
      <webElementGuid>354083f9-af26-41f8-a88c-6af8961da07f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_subject']</value>
      <webElementGuid>cc13644e-76a3-4968-9fc2-5cae06b6c8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>62f3ed27-7e06-4ba2-8ebb-68448fec853d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>6d2cb3ed-7a26-43d6-8df1-0cb7785b5daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_subject' and @type = 'text']</value>
      <webElementGuid>74b6d86c-e121-4aff-b480-cdf345acded7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
