<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_test_1</name>
   <tag></tag>
   <elementGuidId>15529a33-7e02-4cd7-9be4-34515bc91d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_feedback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='basic_feedback']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ca6e3a4b-e723-47cd-885e-ec6cbbb4a028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9ad90be0-451f-4048-b664-aa7ed0957044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_feedback</value>
      <webElementGuid>f83bb63f-79e3-4d59-bc18-4264399dc4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success css-1lq7emp</value>
      <webElementGuid>ed64d9a6-16cc-4687-919e-141bdbb044a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>a70f4fad-a58b-4fef-8126-54f40e4d82df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_feedback&quot;)</value>
      <webElementGuid>6765ac7f-d5a0-44ed-8bae-8dfb5d68b3fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='basic_feedback']</value>
      <webElementGuid>e13be08d-0886-4993-b08b-d2e0680c139d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[5]/div/div[2]/div/div/span/textarea</value>
      <webElementGuid>e8796c2f-a054-42b2-becc-c227f204874b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::textarea[1]</value>
      <webElementGuid>0db99358-0581-498d-8f8c-aab4058eb5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::textarea[1]</value>
      <webElementGuid>9450eae5-d432-4d54-a07f-cf201294ca1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Negara'])[1]/preceding::textarea[1]</value>
      <webElementGuid>fefe7f8d-2427-4e28-9e89-6bde7fba5963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kota'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3ec72164-69f6-4bbe-8487-8d05bf17d828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/span/textarea</value>
      <webElementGuid>b09ad85a-ff30-41c6-b27d-5372a947e8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'basic_feedback' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>78fdf2bd-2d28-4e83-8b27-63dd77186233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
