<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_jakarta</name>
   <tag></tag>
   <elementGuidId>27a7fa01-e5fc-4cc8-bb9d-43056d730a7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_field_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='basic_field_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>66a71739-1944-4ae6-b7c1-b8683571e01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_field_3</value>
      <webElementGuid>fbb436ba-3718-448b-9cfe-82a9a50ba9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success css-1lq7emp</value>
      <webElementGuid>7eea93da-8e98-447c-b7fd-ef26e5960d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jakarta</value>
      <webElementGuid>f454bb9e-ae3b-44b3-9469-0c85f83ccf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_field_3&quot;)</value>
      <webElementGuid>ef6027f9-ef29-4196-adf0-79bc907a7e4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='basic_field_3']</value>
      <webElementGuid>721d5680-7934-4bc5-808d-f7323bffdc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[8]/div/div[2]/div/div/textarea</value>
      <webElementGuid>952e88ad-867f-429a-98e8-73504fd8bb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alamat'])[1]/following::textarea[1]</value>
      <webElementGuid>e74db631-ee46-4890-b39e-26cf45991e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kota'])[1]/following::textarea[1]</value>
      <webElementGuid>8b6a6d0e-0f8f-42d3-b0ec-863e446c9a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sentiment'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c303c31c-b304-47f8-91ee-8d1670d80ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positive'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3e67ff4f-ece5-46dc-ac83-883dfc894c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jakarta']/parent::*</value>
      <webElementGuid>b314b38f-e25f-4c17-865e-aa6c15dec125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/textarea</value>
      <webElementGuid>1f2debb7-11ff-422a-9311-c960947b80c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'basic_field_3' and (text() = 'jakarta' or . = 'jakarta')]</value>
      <webElementGuid>c71215d6-43ce-4a12-af07-f45cb84731e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
