<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tenant</name>
   <tag></tag>
   <elementGuidId>5a7e6c66-ead8-4a1e-a87e-c1d53d39ac32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_tenant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_tenant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d6e7c28-c69f-4853-a37d-87b8a0f8705f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Tenant Code</value>
      <webElementGuid>6d6f7151-2fb1-4446-b1f8-1a80f26fe5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_tenant</value>
      <webElementGuid>27334563-0130-4c74-a912-e50a31bf38bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>959cce88-8313-42c8-921e-a9d47961c921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1qb5nhr</value>
      <webElementGuid>0c334465-a86b-4e11-b72c-89c57df50e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9600226-eb72-4a7c-9f7b-3eef8b685865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>d</value>
      <webElementGuid>e8dd322b-d5cc-4d18-a2d0-c574bfa5c606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_tenant&quot;)</value>
      <webElementGuid>bc3c19e9-4521-40c2-aad7-a5cc2c86a1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_tenant']</value>
      <webElementGuid>02a533dd-9027-4dda-a723-c3b32fd8ce58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>e96d552c-511a-401d-bc4b-7fb87cf53e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3e42d7bc-3902-48b5-a592-2deae41bf395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Tenant Code' and @id = 'basic_tenant' and @type = 'text']</value>
      <webElementGuid>2c118b6e-ccae-48ce-b31f-ce4416a06861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
