<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>e4b5e031-3bb0-4b06-ab6a-ef4a49cd24c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7278be8d-2a43-4e4e-aff2-0416c3bb7ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9bbfbae8-8a4e-4475-a2e4-0f6eab448f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input your password here</value>
      <webElementGuid>c39a64f3-f679-4953-9082-a1511dddec89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_password</value>
      <webElementGuid>1f3aaff2-70aa-470f-9e8e-2c53900fb260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d446235-ba70-4ba4-b625-669fab501a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>06421af3-96ba-4d5f-aeea-735aa0fd8db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1qb5nhr</value>
      <webElementGuid>4209a185-e281-4362-8422-ddd3e2e8773a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_password&quot;)</value>
      <webElementGuid>0ff4c526-ec5c-4a70-bf71-cecf46165d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_password']</value>
      <webElementGuid>bbc9591a-1829-46bf-8de8-f6b8ed3a0dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[4]/div/div/div/div/span/input</value>
      <webElementGuid>1622214c-bcc8-4c3f-8cee-2f372309b32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/span/input</value>
      <webElementGuid>b1c9a14c-a972-4d60-87eb-03312b27994a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Input your password here' and @id = 'basic_password' and @type = 'password']</value>
      <webElementGuid>ea3ddf14-2488-4a61-aa01-b77d9d9c7ca2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
